apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
  finalizers: # Finalizer that ensures that project is not deleted until it is not referenced by any application
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:  # Allow manifests to deploy from any Git repos
  - '*'
  destinations: # Only permit applications to deploy to the guestbook namespace in the same cluster
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*' 
  orphanedResources:
    warn: true